/* =====================================================================
   9. 화면 : 메뉴는 사업 프로필로 구성
   ===================================================================== */
let cur="home", curSec="", outTab="", setupTab="basic", PRIOR=null, BUSY="";
function menu(){
  const v=[]; if(!P)return v; const M=prof().modules;
  v.push({g:"준비",id:"home",k:"00",t:"개요·점검"});
  if((dat().findings||[]).length)v.push({g:"준비",id:"verify",k:"✓",t:"문서 대조 결과"});
  v.push({g:"준비",id:"map",k:"01",t:"서식 매칭 맵"},{g:"준비",id:"meta",k:"02",t:"기본정보"},{g:"준비",id:"setup",k:"03",t:"사업 구조 설정"});
  let i=4; const add=(id,t)=>v.push({g:"공통 데이터",id,k:String(i++).padStart(2,"0"),t});
  if(M.tasks.on)add("tasks",M.tasks.label); if(M.kpi.on)add("kpi",M.kpi.label); if(M.finance.on)add("finance",M.finance.label); if(M.bonus&&M.bonus.on&&vOK(M.bonus))add("bonus",M.bonus.label); if(M.gov.on)add("gov",M.gov.label);
  prof().docs.forEach((d,j)=>v.push({g:"문서 작성",id:"doc:"+d.id,k:d.type==="report"?"R":"P",t:d.name}));
  v.push({g:"문서 작성",id:"out",k:"↓",t:"문서 생성·내보내기"});
  return v;
}
function navDot(id){
  const L=checks(); const M=prof().modules; const map={tasks:M.tasks.label,kpi:M.kpi.label,finance:"재정|장비",bonus:M.bonus.label,gov:M.gov.label};
  if(map[id]){const re=new RegExp(map[id].replace(/[()]/g,"."));const rel=L.filter(x=>re.test(x.area));if(!rel.length)return "";return rel.some(x=>x.lv==="bad")?"bad":rel.some(x=>x.lv==="warn")?"warn":"ok"}
  if(id.startsWith("doc:")){const doc=docById(id.slice(4));if(!doc)return "";const st=visibleSecs(doc).map(s=>secStatus(doc,s)).filter(Boolean);return st.includes("bad")?"bad":st.includes("warn")?"warn":"ok"}
  return "";
}
function renderTop(){
  const ps=$("#projSel"); ps.innerHTML=(P&&P.demo?`<option value="" selected>${esc(P.name)}</option>`:"")+PROJ.map(p=>`<option value="${esc(p.id)}" ${P&&p.id===P.id?"selected":""}>${esc(p.name)}</option>`).join("")||`<option value="">사업 없음</option>`;
  $("#chipUniv").textContent=P?[dat().meta.org||prof().orgLabel||"기관",dat().meta.variant].filter(Boolean).join(" · "):"기관"; 
  $("#brandSub").textContent=P&&prof().planTitle?prof().planTitle:"기본계획 · 평가(실적)보고서 · 사업계획서 연계 표준 자동화";
}
function renderNav(){ let g="",h=""; menu().forEach(v=>{ if(v.g!==g){g=v.g;h+=`<div class="navgrp">${esc(g)}</div>`} const d=navDot(v.id); h+=`<button class="navbtn ${cur===v.id?"on":""}" data-go="${esc(v.id)}"><span class="k">${esc(v.k)}</span>${esc(v.t)}${d?`<span class="dot ${d}"></span>`:""}</button>`; }); $("#nav").innerHTML=h; }
function head(eb,t,p,extra){return `<div class="vhead"><div style="flex:1;min-width:240px"><div class="eyebrow">${esc(eb)}</div><h2>${esc(t)}</h2>${p?`<p>${p}</p>`:""}</div>${extra||""}</div>`}
const V={};

/* ── 시작 / 새 사업 ── */
V.welcome=()=>head("표준 보고서 자동화","시작할 사업을 고르세요","사업마다 기본계획과 작성 서식이 달라도 같은 방식으로 씁니다. 내장 템플릿으로 시작하거나, 다른 재정지원사업의 기본계획·서식 파일을 올려 구조를 만드세요.")+V.newproj(true);
V.newproj=(inline)=>`${inline?"":head("새 사업","새 사업 만들기","사업 구조(평가영역·집행기준·문서 목차·공통 데이터)는 만든 뒤 ‘사업 구조 설정’에서 파일을 올려 자동으로 채우거나 직접 고칠 수 있습니다.")}
  <div class="panel demo-card" style="margin-bottom:16px"><div class="row" style="justify-content:space-between"><div><h3 style="margin:0">처음이라면 데모부터</h3><p class="small" style="margin:4px 0 0">가상 대학 데이터로 전체 흐름(점검 → 매칭 → 공통 데이터 → 문서 작성 → 생성)을 10단계로 안내하고, 예시 서식으로 구조 분석까지 눌러 봅니다. 데모에서 입력한 내용은 저장되지 않습니다.</p></div><button class="btn pri" data-act="startDemo">데모 체험 시작</button></div></div>
  <div class="grid2"><div class="panel"><h3>내장 템플릿으로 시작</h3><p class="small muted" style="margin:0 0 10px">구조가 이미 정리된 사업입니다. 기관 데이터만 채우면 됩니다.</p>${Object.values(TEMPLATES).map(t=>`<div class="row" style="justify-content:space-between;border-top:1px solid var(--line);padding-top:8px;margin-top:8px"><div><b>${esc(t.programName)}</b><div class="small muted">${esc(t.planTitle)} · 문서 ${t.docs.length}종</div></div><button class="btn pri sm" data-act="createFrom" data-key="${esc(t.key)}">이 템플릿으로 만들기</button></div>`).join("")}</div>
  <div class="panel"><h3>다른 재정지원사업 (파일에서 만들기)</h3><p class="small muted" style="margin:0 0 10px">빈 프로필로 사업을 만든 뒤 기본계획(안)과 작성 서식(HWP·HWPX·PDF·DOCX·ZIP)을 올려 구조를 뽑습니다.</p><label class="f">사업 이름<input id="newName" type="text" placeholder="예) 2026 RISE 사업, LINC 3.0, 고교교육 기여대학 지원사업"></label><button class="btn pri" style="margin-top:10px" data-act="createBlank">빈 프로필로 만들고 파일 올리기</button></div></div>`;

/* ── 개요 ── */
V.home=()=>{
  const pr=prof(), L=checks(); const bad=L.filter(x=>x.lv==="bad").length, warn=L.filter(x=>x.lv==="warn").length;
  const docStats=pr.docs.map(d=>{const st=visibleSecs(d).map(s=>secStatus(d,s)).filter(Boolean);return {d,p:st.length?Math.round(st.filter(x=>x==="ok").length/st.length*100):0}});
  const bonus=pr.modules.bonus; const bo=bonus&&bonus.on&&bonus.table&&vOK(bonus)?calcBonus():null;
  return head(pr.programName||"사업명 미정",`${ORG()} 작성 현황`,`${esc(pr.goal||"기본계획의 평가요소를 기준으로 평가(실적)보고서와 사업계획서를 하나의 데이터로 작성합니다.")}`, dat().preset?`<div class="row"><span class="small muted">${esc(dat().preset)}</span>${(dat().findings||[]).length?`<button class="btn sm" data-go="verify">문서 대조 결과</button>`:""}</div>`:"")+
  `<div class="stack">${pr.schedule.length?`<div class="timeline">${pr.schedule.map(s=>`<div class="tl ${s.now?"now":""}"><div class="d">${esc(s.d)}</div><div class="w">${esc(s.w)}</div><div class="small muted">${esc(s.s)}</div></div>`).join("")}</div>`:""}
  ${pr.docs.length?"":`<div class="empty-state"><b>아직 문서 구조가 없습니다.</b><p class="small">기본계획과 작성 서식을 올리면 평가영역, 집행기준, 문서 목차가 자동으로 만들어집니다.</p><button class="btn pri" data-go="setup">사업 구조 설정으로 이동</button></div>`}
  ${pr.docs.length?batchBoxHTML():""}
  <div class="grid3">${docStats.map(x=>`<div class="panel stat"><span class="small muted">${esc(x.d.name)} ${x.d.due?"("+esc(x.d.due)+")":""}</span><span class="v">${x.p}%</span><div class="meter"><i style="width:${x.p}%"></i></div><span class="small muted">${x.d.pageLimit?"본문 "+x.d.pageLimit+"쪽 이내":"분량 기준 미설정"}</span></div>`).join("")}
  <div class="panel stat"><span class="small muted">점검 결과</span><span class="v">${bad?`<span style="color:var(--bad)">${bad}</span>`:"0"} <span class="small">오류</span> · ${warn} <span class="small">확인</span></span><span class="small muted">${bo?`예상 ${esc(bonus.label)} ${bo.pts==null?"-":bo.pts+"점"}`:Store.mode==="db"?"데이터는 이 아티팩트 저장소에 보관":"데이터는 이 브라우저에 보관"}</span></div></div>
  <div class="grid2"><div class="panel"><h3>평가 구조</h3>${pr.evalAreas.length?`<div class="tw"><table class="t"><tr><th>영역</th><th class="n">배점</th><th>평가 내용</th></tr>${pr.evalAreas.filter(vOK).map(a=>`<tr><td><b>${esc(a.name)}</b><div class="small muted">${esc(a.how)}</div></td><td class="n num">${a.bonus?"+":""}${a.pts||"-"}</td><td class="small">${esc(a.desc)}</td></tr>`).join("")}</table></div>`:'<p class="small muted">평가영역이 없습니다. 기본계획을 올려 분석하세요.</p>'}${pr.grades?`<p class="small muted" style="margin:8px 0 0">${esc(pr.grades)}</p>`:""}</div>
  <div class="panel"><h3>제출 전 점검</h3><div class="checks">${L.map(x=>`<div class="chk">${pill(x.lv==="ok"?"ok":x.lv==="warn"?"warn":"bad",x.area)}<span class="small">${esc(x.msg)}</span><button class="btn ghost sm" data-go="${esc(x.go)}">이동</button></div>`).join("")||'<p class="small muted">점검 항목이 없습니다.</p>'}</div></div></div></div>`;
};
V.verify=()=>{ const F=dat().findings||[]; const c=k=>F.filter(x=>x.lv===k).length;
  return head("원문 문서 ↔ 서식·기본계획 대조",`${ORG()} 문서 대조 결과`,`${esc(dat().preset||"")}`,`<button class="btn sm" data-act="clearFindingsAsk">대조 결과 지우기</button>`)+
  `<div class="grid3" style="margin-bottom:16px"><div class="panel stat"><span class="small muted">수정 필요</span><span class="v" style="color:var(--bad)">${c("bad")}</span></div><div class="panel stat"><span class="small muted">확인·보완</span><span class="v" style="color:var(--warn)">${c("warn")}</span></div><div class="panel stat"><span class="small muted">적합</span><span class="v" style="color:var(--ok)">${c("ok")}</span></div></div>
  <div class="tw"><table class="t"><tr><th>판정</th><th style="min-width:84px">영역</th><th style="min-width:280px">발견 내용</th><th style="min-width:160px">근거 위치</th><th style="min-width:220px">작성 시 조치</th></tr>${F.map(x=>`<tr><td>${lvPill(x.lv)}</td><td class="small">${esc(x.area)}</td><td class="small">${esc(x.msg)}</td><td class="small muted">${esc(x.src)}</td><td class="small">${esc(x.fix)}</td></tr>`).join("")}</table></div>`; };

/* ── 매칭 맵 (프로필에서 자동 생성) ── */
V.map=()=>{ const pr=prof(); const reps=pr.docs.filter(d=>d.type==="report"), plans=pr.docs.filter(d=>d.type==="plan");
  const rowsFor=(areaId)=>{ const out=[]; reps.forEach(d=>visibleSecs(d).filter(s=>s.evalArea===areaId&&s.kind!=="head").forEach(s=>{ const to=[]; plans.forEach(pd=>visibleSecs(pd).forEach(ps=>{ if(ps.from.includes(d.id+":"+s.id))to.push({pd,ps}); })); out.push({d,s,to}); })); return out; };
  const areas=pr.evalAreas.filter(vOK).concat([{id:"",name:"평가영역 미지정",desc:"",pts:""}]);
  const body=areas.map(a=>{ const rs=rowsFor(a.id); if(!rs.length&&a.id)return `<div class="flow maprow"><div class="cell pl"><span class="pill ${a.bonus?"warn":"ok"}">${esc(a.name)} ${a.pts?(a.bonus?"+":"")+a.pts:""}</span><div class="small" style="margin-top:4px">${esc(a.desc)}</div></div><div class="arrow">→</div><div class="cell rp"><span class="pill bad">연결된 항목 없음</span> <button class="btn ghost sm" data-go="setup" data-tab="docs">목차에서 연결</button></div><div class="arrow"></div><div class="cell ap muted small">-</div></div>`; if(!rs.length)return "";
    return rs.map((r,i)=>{ const st=secStatus(r.d,r.s); return `<div class="flow maprow"><div class="cell pl">${i===0?`<span class="pill ${a.bonus?"warn":a.id?"ok":"n"}">${esc(a.name)} ${a.pts?(a.bonus?"+":"")+a.pts:""}</span><div class="small" style="margin-top:4px">${esc(a.desc)}</div>`:'<span class="small muted">〃</span>'}</div><div class="arrow">→</div><div class="cell rp"><div class="h">${esc(r.s.no)} ${esc(r.s.title)} ${st?pill(st==="ok"?"ok":st==="warn"?"warn":"bad",st==="ok"?"작성":"미흡"):""}</div><div class="small muted">${esc(r.d.name)}</div><button class="btn ghost sm" data-go="${r.s.kind==="auto"?({tasks:"tasks",kpi:"kpi",gov:"gov",budget:"finance",bonus:"bonus"}[r.s.src]||"doc:"+r.d.id+":"+r.s.id):"doc:"+r.d.id+":"+r.s.id}">작성하기</button></div><div class="arrow">${r.to.length?"→":""}</div><div class="cell ap">${r.to.map(x=>`<div class="h">${esc(x.ps.no)} ${esc(x.ps.title)}</div><div class="small muted">${esc(x.pd.name)}</div>`).join("")||'<span class="small muted">다음 문서 연결 없음</span>'}</div></div>`; }).join(""); }).join("");
  return head("기본계획 → "+(reps.map(d=>d.name).join(", ")||"보고서")+" → "+(plans.map(d=>d.name).join(", ")||"계획서"),"서식 매칭 맵","기본계획의 평가영역이 보고서의 어느 항목에서 평가되고, 그 항목의 계획 내용이 다음 사업계획서의 어느 항목으로 이어지는지 사업 구조에서 자동으로 그립니다.")+
  `<div class="maphead"><span>기본계획 평가영역</span><span></span><span>평가(실적) 보고서</span><span></span><span>사업계획서</span></div>${body||'<div class="empty-state">평가영역이나 문서 목차가 없습니다. 사업 구조 설정에서 만드세요.</div>'}`; };

/* ── 기본정보 ── */
V.meta=()=>{ const pr=prof(); const alt=pr.rules.find(r=>r.altMax);
  return head("표지 · 요약 · 기준금액","기본정보","모든 문서의 표지와 요약표, 재정 검증 기준에 쓰입니다.")+
  `<div class="stack"><div class="panel"><h3>${esc(pr.orgLabel||"기관")} 및 총괄책임자</h3><div class="fg">
  <label class="f">${esc(pr.orgLabel||"기관")}명${inp("data.meta.org",{ph:"○○대학교"})}</label>
  ${pr.variants&&pr.variants.length?`<label class="f">${esc(pr.variantLabel||"구분")}${sel("data.meta.variant",[""].concat(pr.variants))}</label>`:""}
  <label class="f">주소${inp("data.meta.addr")}</label><label class="f">URL${inp("data.meta.url")}</label>
  <label class="f">총괄책임자 소속(직위)${inp("data.meta.leaderOrg")}</label><label class="f">성명${inp("data.meta.leaderName")}</label><label class="f">연락처${inp("data.meta.phone")}</label></div></div>
  <div class="panel"><h3>재정 기준금액 <span class="small muted">(백만원)</span></h3><div class="fg">
  <label class="f">${esc(pr.years.prev)} 최종 사업비 총액${inp("data.meta.totalPrev",{num:1})}</label><label class="f">${esc(pr.years.cur)} 사업비(확정 안내액)${inp("data.meta.budgetCur",{num:1})}</label><label class="f">전년도 이월금${inp("data.meta.carry",{num:1})}</label>
  ${alt?`<label class="f">${esc(pr.years.cur)} ${esc(alt.altLabel||"예외 조건")}${sel("data.meta.flag",["O","X"])}</label><label class="f">${esc(pr.years.prev)} ${esc(alt.altLabel||"예외 조건")}${sel("data.meta.flagPrev",["O","X"])}</label>`:""}</div>
  ${alt?`<p class="small muted" style="margin:10px 0 0">${esc(alt.altLabel)} 해당 시 ${esc(alt.label)} 한도가 ${alt.max}%에서 ${alt.altMax}%로 바뀝니다.</p>`:""}</div>
  <div class="panel"><h3>생성형 AI 활용 각주</h3>${ta("data.meta.aiNote","예) 초안 문장 다듬기에 생성형 AI 활용, 수치·사실은 담당자가 원자료로 검증",2)}</div></div>`; };

/* ── 사업 구조 설정 (업로드 · 분석 · 프로필 편집) ── */
V.setup=()=>{ const pr=prof(); const plans=SOURCES.filter(s=>s.role==="plan").length, forms=SOURCES.filter(s=>s.role==="form").length, priors=SOURCES.filter(s=>s.role==="prior").length;
  const steps=[["1. 파일 올리기",`기본계획 ${plans} · 서식 ${forms} · 전년도 ${priors}`,SOURCES.length>0],["2. 구조 분석","평가영역·집행기준·목차",pr.docs.length>0],["3. 구조 확인·수정","아래 편집 탭",pr.docs.length>0&&pr.evalAreas.length>0],["4. 전년도 데이터 추출","과제·지표·재정·대조",(dat().findings||[]).length>0]];
  const tabs=[["basic","기본 정보"],["areas","평가영역"],["rules","집행기준·비목"],["docs","문서·목차"],["modules","공통 데이터 모듈"],["sched","일정·작성 항목"]];
  return head("사업 구조 = 메뉴 구성",`${pr.programName||"새 사업"} 구조 설정`,"기본계획(안)과 작성 서식을 올리면 이 사업의 평가영역, 집행기준, 문서 목차, 공통 데이터 모듈이 만들어지고 왼쪽 메뉴가 그에 맞춰 바뀝니다.",`<div class="row"><button class="btn sm" data-act="exportProfile">구조 내보내기</button><button class="btn sm" data-act="importAsk">불러오기</button><span id="delSlot"><button class="btn sm" data-act="delProjAsk">이 사업 삭제</button></span></div>`)+
  `<div class="steps">${steps.map((s,i)=>`<div class="step ${s[2]?"done":""}"><b>${esc(s[0])}</b>${esc(s[1])}</div>`).join("")}</div>
  <div class="grid2"><div class="panel"><h3>1. 파일 올리기</h3><div class="dz" id="dz" data-act="pickFiles" role="button" tabindex="0">여기에 파일을 끌어다 놓거나 눌러서 고르세요<div class="small muted">PDF · HWP · HWPX · DOCX · XLSX · CSV · TXT · ZIP(서식 묶음)</div></div>
    ${BUSY?`<p class="busy">${esc(BUSY)}</p>`:""}
    <div class="fl" style="margin-top:10px">${SOURCES.map(s=>`<div><div class="fi"><span class="nm small" title="${esc(s.name)}">${esc(s.name)} <span class="muted">${s.error?"· "+esc(s.error):"· "+(s.chars||0).toLocaleString()+"자"+(s.truncated?"(일부 저장)":"")}</span></span><select data-srcrole="${esc(s.id)}" aria-label="문서 역할">${Object.entries(ROLE_LABEL).map(([k,l])=>`<option value="${k}" ${s.role===k?"selected":""}>${l}</option>`).join("")}</select><button class="btn ghost sm" data-act="srcPrev" data-id="${esc(s.id)}">보기</button><button class="btn ghost sm" data-act="srcDel" data-id="${esc(s.id)}">삭제</button></div>${s._open?`<pre class="prev">${esc((s.text||"").slice(0,4000))}</pre>`:""}</div>`).join("")||'<p class="small muted">아직 올린 파일이 없습니다.</p>'}</div></div>
  <div class="panel"><h3>2. 구조 분석</h3><p class="small muted" style="margin:0 0 10px">규칙 분석은 목차·작성방법·배점·비목 한도(%)를 문장 패턴으로 찾습니다. Claude 분석은 서식 지시문까지 읽어 항목 종류와 문서 간 연결을 더 정확히 잡습니다. 어느 쪽이든 결과는 아래 탭에서 고칠 수 있습니다.</p>
    <div class="row"><button class="btn" data-act="ruleAnalyze" ${plans+forms?"":"disabled"}>규칙으로 구조 만들기</button><button class="btn pri" data-act="claudeAnalyze" id="btnClaude" ${plans+forms?"":"disabled"}>Claude로 정밀 분석</button></div>
    <h3 style="margin-top:16px">4. 전년도 제출 문서에서 데이터 추출</h3><p class="small muted" style="margin:0 0 10px">전년도 보고서·계획서를 ‘전년도 제출 문서’로 올리면 Claude가 ${esc(pr.modules.tasks.label)}, ${esc(pr.modules.kpi.label)}, 비목 예산, 조직을 뽑고 문서 간 불일치를 찾아 ‘문서 대조 결과’로 정리합니다.</p>
    <button class="btn pri" data-act="priorExtract" ${priors?"":"disabled"}>전년도 문서 분석</button>
    ${PRIOR?`<div class="guide" style="margin-top:10px"><b>추출 결과 미리보기</b><p style="margin:4px 0">${esc(pr.modules.tasks.label)} ${(PRIOR.tasks||[]).length}개 · ${esc(pr.modules.kpi.label)} ${(PRIOR.kpi||[]).length}개 · 비목 ${Object.keys(PRIOR.b1||{}).length}개 · 조직 ${(PRIOR.gov||[]).length}개 · 대조 결과 ${(PRIOR.findings||[]).length}건</p><div class="row"><button class="btn pri sm" data-act="applyPrior">현재 사업에 적용</button><button class="btn sm" data-act="dropPrior">버리기</button></div><p class="small muted" style="margin:6px 0 0">적용하면 같은 종류의 기존 입력을 이 결과로 바꿉니다.</p></div>`:""}
    <p class="small muted" id="sampleNote" style="margin-top:10px"></p></div></div>
  <div class="panel" style="margin-top:16px"><h3>3. 구조 확인·수정</h3><div class="tabs">${tabs.map(([k,t])=>`<button class="tab ${setupTab===k?"on":""}" data-stab="${k}">${t}</button>`).join("")}</div>${SETUP[setupTab]()}</div>`; };
const KINDS=[["head","제목만"],["text","서술"],["pp","성과+계획"],["auto","공통 데이터 표"],["derived","보고서 계획 모아쓰기"]];
const SRCS=[["",""],["tasks","과제(이행점검/총괄표)"],["kpi","성과지표"],["gov","조직·거버넌스"],["budget","사업비·재정"],["summary","요약표"],["bonus","가산점"]];
const SETUP={
  basic(){ return `<div class="fg"><label class="f">사업명${inp("profile.programName")}</label><label class="f">기본계획 제목${inp("profile.planTitle")}</label><label class="f">사업기간${inp("profile.period")}</label><label class="f">수행기관 호칭${inp("profile.orgLabel",{ph:"대학, 기관, 컨소시엄"})}</label>
    <label class="f">전년도 표기${inp("profile.years.prev",{ph:"’25"})}</label><label class="f">금년도 표기${inp("profile.years.cur",{ph:"’26"})}</label><label class="f">차년도 표기${inp("profile.years.next",{ph:"’27"})}</label>
    <label class="f">기관 구분 명칭${inp("profile.variantLabel",{ph:"권역, 유형"})}</label><label class="f">구분 값 (쉼표로)<input id="i_variants" type="text" data-b="profile.variants" data-csv="1" value="${esc((prof().variants||[]).join(", "))}"></label></div>
    <label class="f" style="margin-top:10px">사업 목표${ta("profile.goal","",2)}</label><label class="f" style="margin-top:10px">평가 등급·결과 활용${inp("profile.grades")}</label>`; },
  areas(){ return `<div class="tw"><table class="t"><tr><th>id</th><th style="min-width:160px">평가영역</th><th>배점</th><th>가산점</th><th style="min-width:120px">평가방식</th><th style="min-width:240px">평가 내용</th><th style="min-width:200px">주안점(줄마다)</th><th>적용 구분</th><th></th></tr>${prof().evalAreas.map((a,i)=>`<tr><td class="in" style="width:56px">${inp(`profile.evalAreas.${i}.id`,{aria:"id"})}</td><td class="in">${inp(`profile.evalAreas.${i}.name`,{aria:"영역"})}</td><td class="in" style="width:64px">${inp(`profile.evalAreas.${i}.pts`,{num:1,aria:"배점"})}</td><td><input type="checkbox" data-b="profile.evalAreas.${i}.bonus" data-bool="1" ${a.bonus?"checked":""} aria-label="가산점"></td><td class="in">${inp(`profile.evalAreas.${i}.how`,{aria:"방식"})}</td><td class="in">${ta(`profile.evalAreas.${i}.desc`,"",2)}</td><td class="in">${ta(`profile.evalAreas.${i}.focus`,"",2,true)}</td><td class="in" style="width:90px">${inp(`profile.evalAreas.${i}.onlyVariant`,{aria:"구분"})}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="profile.evalAreas" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="profile.evalAreas" data-tpl='{"id":"","name":"","pts":0,"how":"","desc":"","focus":[]}'>영역 추가</button>`; },
  rules(){ const pr=prof(); return `<div class="tw"><table class="t"><tr><th style="min-width:130px">기준</th><th style="min-width:150px">비목 찾기(정규식)</th><th>한도(%)</th><th>예외 한도</th><th style="min-width:120px">예외 조건</th><th>종류</th><th style="min-width:200px">근거</th><th></th></tr>${pr.rules.map((r,i)=>`<tr><td class="in">${inp(`profile.rules.${i}.label`,{aria:"기준"})}</td><td class="in">${inp(`profile.rules.${i}.kw`,{aria:"정규식"})}</td><td class="in" style="width:70px">${inp(`profile.rules.${i}.max`,{num:1,aria:"한도"})}</td><td class="in" style="width:70px">${inp(`profile.rules.${i}.altMax`,{num:1,aria:"예외 한도"})}</td><td class="in">${inp(`profile.rules.${i}.altLabel`,{aria:"예외 조건"})}</td><td class="in">${sel(`profile.rules.${i}.type`,[["limit","비목 한도"],["carry","이월 한도"]],"종류")}</td><td class="in">${inp(`profile.rules.${i}.basis`,{aria:"근거"})}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="profile.rules" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="profile.rules" data-tpl='{"id":"","label":"","kw":"","max":10,"type":"limit","basis":""}'>기준 추가</button>
    <div class="grid2" style="margin-top:14px"><label class="f">전년도 실적 비목 (줄마다)${ta("profile.budgetItems","",7,true)}</label><label class="f">금년도 계획 비목 (줄마다, 인건비 세분 가능)${ta("profile.budgetPlanItems","",7,true)}</label><label class="f">예산 영역 (줄마다)${ta("profile.budgetAreas","",4,true)}</label><label class="f">연도 열 이름 (줄마다 3개)${ta("profile.budgetYears","",4,true)}</label></div>
    <div class="fg" style="margin-top:10px"><label class="f">사전 승인 장비 기준(백만원)${inp("profile.equipThreshold",{num:1})}</label><label class="f">비목 편중 경고 기준(%)${inp("profile.concentration",{num:1})}</label></div>`; },
  docs(){ const pr=prof(); const grp=[["",""]].concat((pr.modules.tasks.groups||[]).map(g=>[g.area,g.area+(g.variant?" ("+g.variant+")":"")])).filter((x,i,a)=>a.findIndex(y=>y[0]===x[0])===i); const ar=[["",""]].concat(pr.evalAreas.map(a=>[a.id,a.name]));
    return pr.docs.map((d,di)=>`<div class="panel" style="margin-bottom:12px;background:var(--paper)"><div class="fg"><label class="f">문서명${inp(`profile.docs.${di}.name`)}</label><label class="f">종류${sel(`profile.docs.${di}.type`,[["report","평가·실적 보고서"],["plan","사업계획서"]])}</label><label class="f">제출기한${inp(`profile.docs.${di}.due`)}</label><label class="f">본문 분량 한도(쪽)${inp(`profile.docs.${di}.pageLimit`,{num:1})}</label><label class="f">표지 문구 (줄마다)${ta(`profile.docs.${di}.cover`,"",2,true)}</label></div>
      <div class="tw" style="margin-top:10px"><table class="t"><tr><th>번호</th><th style="min-width:200px">목차 제목</th><th>종류</th><th>공통 데이터</th><th>과제 영역</th><th>과제 수</th><th>평가영역</th><th style="min-width:130px">연결 원천(문서:항목)</th><th>적용 구분</th><th style="min-width:220px">작성방법(줄마다)</th><th></th></tr>
      ${d.sections.map((s,si)=>{const b=`profile.docs.${di}.sections.${si}`;return `<tr><td class="in" style="width:80px">${inp(b+".no",{aria:"번호"})}<div class="small muted">${esc(s.id)}</div></td><td class="in">${inp(b+".title",{aria:"제목"})}</td><td class="in">${sel(b+".kind",KINDS,"종류")}</td><td class="in">${sel(b+".src",SRCS,"공통 데이터")}</td><td class="in">${sel(b+".group",grp,"과제 영역")}</td><td class="in" style="width:56px">${inp(b+".keys",{num:1,aria:"과제 수"})}</td><td class="in">${sel(b+".evalArea",ar,"평가영역")}</td><td class="in"><input type="text" data-b="${b}.from" data-csv="1" value="${esc(s.from.join(", "))}" aria-label="연결 원천"></td><td class="in" style="width:80px">${inp(b+".onlyVariant",{aria:"구분"})}</td><td class="in">${ta(b+".guide","",2,true)}</td><td><div class="row" style="gap:2px"><button class="btn ghost sm" data-act="rowUp" data-arr="profile.docs.${di}.sections" data-i="${si}" aria-label="위로">▲</button><button class="btn ghost sm" data-act="rowDel" data-arr="profile.docs.${di}.sections" data-i="${si}">삭제</button></div></td></tr>`}).join("")}</table></div>
      <div class="row" style="margin-top:8px"><button class="btn sm" data-act="secAdd" data-di="${di}">항목 추가</button><button class="btn ghost sm" data-act="rowDel" data-arr="profile.docs" data-i="${di}">이 문서 삭제</button><span class="small muted">연결 원천 예: ${esc(pr.docs[0]?pr.docs[0].id+":"+(pr.docs[0].sections[0]||{id:"s1"}).id:"d1:s1")}</span></div></div>`).join("")+`<button class="btn" data-act="docAdd">문서 추가</button>`; },
  modules(){ const M=prof().modules; const tog=(k)=>`<label class="row small"><input type="checkbox" data-b="profile.modules.${k}.on" data-bool="1" ${M[k].on?"checked":""}> 사용</label>`;
    return `<div class="grid2"><div class="panel"><h3>과제 관리 ${tog("tasks")}</h3><div class="fg"><label class="f">메뉴 이름${inp("profile.modules.tasks.label")}</label><label class="f">표시 문구${inp("profile.modules.tasks.mark",{ph:"핵심"})}</label></div>
      <div class="tw" style="margin-top:8px"><table class="t"><tr><th>세부영역</th><th>목차 번호</th><th>지정 수</th><th>적용 구분</th><th></th></tr>${(M.tasks.groups||[]).map((g,i)=>`<tr><td class="in">${inp(`profile.modules.tasks.groups.${i}.area`,{aria:"세부영역"})}</td><td class="in" style="width:80px">${inp(`profile.modules.tasks.groups.${i}.sec`,{aria:"번호"})}</td><td class="in" style="width:60px">${inp(`profile.modules.tasks.groups.${i}.n`,{num:1,aria:"수"})}</td><td class="in" style="width:90px">${inp(`profile.modules.tasks.groups.${i}.variant`,{aria:"구분"})}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="profile.modules.tasks.groups" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="profile.modules.tasks.groups" data-tpl='{"area":"","sec":"","n":1,"variant":""}'>세부영역 추가</button></div>
      <div class="panel"><h3>성과지표 ${tog("kpi")}</h3><div class="fg"><label class="f">메뉴 이름${inp("profile.modules.kpi.label")}</label><label class="f">권장 최소 개수${inp("profile.modules.kpi.min",{num:1})}</label><label class="f">권장 최대 개수${inp("profile.modules.kpi.max",{num:1})}</label><label class="f">낮을수록 좋은 지표 단어${inp("profile.modules.kpi.lowerKw")}</label></div></div>
      <div class="panel"><h3>재정 ${tog("finance")}</h3><label class="f">메뉴 이름${inp("profile.modules.finance.label")}</label><p class="small muted">비목·집행기준은 ‘집행기준·비목’ 탭에서 정합니다.</p></div>
      <div class="panel"><h3>조직·거버넌스 ${tog("gov")}</h3><label class="f">메뉴 이름${inp("profile.modules.gov.label")}</label><div class="tw" style="margin-top:8px"><table class="t"><tr><th>대상 조직(정규식)</th><th>필수 구성(정규식)</th><th>이름</th><th></th></tr>${(M.gov.required||[]).map((r,i)=>`<tr><td class="in">${inp(`profile.modules.gov.required.${i}.match`,{aria:"대상"})}</td><td class="in">${inp(`profile.modules.gov.required.${i}.must`,{aria:"필수"})}</td><td class="in">${inp(`profile.modules.gov.required.${i}.label`,{aria:"이름"})}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="profile.modules.gov.required" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="profile.modules.gov.required" data-tpl='{"match":"위원회","must":"","label":""}'>필수 구성 추가</button></div>
      ${M.bonus&&M.bonus.table?`<div class="panel"><h3>가산점 ${tog("bonus")}</h3><label class="f">메뉴 이름${inp("profile.modules.bonus.label")}</label><p class="small muted">가점표는 템플릿에 정의되어 있습니다. 프로필 JSON으로 수정할 수 있습니다.</p></div>`:""}</div>`; },
  sched(){ const pr=prof(); return `<div class="tw"><table class="t"><tr><th>날짜</th><th style="min-width:200px">할 일</th><th>비고</th><th>현재 단계</th><th></th></tr>${pr.schedule.map((s,i)=>`<tr><td class="in" style="width:110px">${inp(`profile.schedule.${i}.d`,{aria:"날짜"})}</td><td class="in">${inp(`profile.schedule.${i}.w`,{aria:"할 일"})}</td><td class="in">${inp(`profile.schedule.${i}.s`,{aria:"비고"})}</td><td><input type="checkbox" data-b="profile.schedule.${i}.now" data-bool="1" ${s.now?"checked":""} aria-label="현재"></td><td><button class="btn ghost sm" data-act="rowDel" data-arr="profile.schedule" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="profile.schedule" data-tpl='{"d":"","w":"","s":""}'>일정 추가</button>
    <h3 style="margin-top:16px">‘성과+계획’ 항목의 입력 칸</h3><div class="tw"><table class="t"><tr><th>키</th><th style="min-width:300px">칸 이름</th><th>짧은 칸</th></tr>${pr.ppFields.map((f,i)=>`<tr><td class="mono small">${esc(f.k)}</td><td class="in">${inp(`profile.ppFields.${i}.l`,{aria:"칸 이름"})}</td><td><input type="checkbox" data-b="profile.ppFields.${i}.short" data-bool="1" ${f.short?"checked":""} aria-label="짧은 칸"></td></tr>`).join("")}</table></div><p class="small muted">f2(금년도 계획)는 사업계획서의 ‘보고서 계획 모아쓰기’ 항목으로 이어집니다.</p>`; }
};

/* ── 공통 데이터 ── */
V.tasks=()=>{ const pr=prof(), M=pr.modules.tasks, y=pr.years; const gs=taskGroups(); const D=dat();
  return head("이행점검 · 총괄표 · 신구대조표",`${M.label} (${gs.reduce((s,a)=>s+a.n,0)}개)`,`세부영역별 지정 개수: ${gs.map(a=>`${esc(a.sec)} ${a.n}개`).join(" · ")||"세부영역이 없습니다(사업 구조 설정 → 공통 데이터 모듈)"}. 여기 입력한 내용이 보고서 이행점검표와 계획서 총괄표에 함께 들어갑니다.`,`<button class="btn pri" data-act="taskAdd">과제 추가</button>`)+
  `<div class="stack">${gs.map(a=>{const ts=D.tasks.map((t,i)=>({t,i})).filter(x=>x.t.group===a.area);return `<div><div class="row" style="margin-bottom:8px"><h3 style="font-size:15px">${esc(a.sec)} ${esc(a.area)}</h3>${pill(ts.length===a.n?"ok":"bad",`${ts.length}/${a.n}`)}</div><div class="grid2">${ts.map(({t,i})=>{const b="data.tasks."+i;return `<div class="taskcard"><div class="hd"><span class="no">과제${esc(t.no||i+1)}</span>${KEYMARK()}<span class="small muted">${esc(keyLabel(t))}</span><span style="flex:1"></span>${pill(!t.status?"n":t.status==="달성"?"ok":t.status==="미달성"?"bad":"warn",t.status||"실적 미입력")}<button class="btn ghost sm" data-act="rowDel" data-arr="data.tasks" data-i="${i}">삭제</button></div>
    <div class="fg"><label class="f">과제 번호${inp(b+".no",{aria:"번호"})}</label><label class="f">세부영역${sel(b+".group",gs.map(x=>x.area))}</label></div>
    <label class="f">과제명 (${esc(y.prev)} 보고서 기준)${inp(b+".name")}</label><label class="f">계획서상 과제명 ${t.planName&&norm(t.planName)!==norm(t.name)?pill("warn","표기 불일치"):""}${inp(b+".planName")}</label>
    <label class="f">계획 목표 (${esc(y.prev)} 보고서 기준)${ta(b+".goal","",2)}</label><label class="f">이행 실적 (제출일 전일 기준)${ta(b+".result","",2)}</label>
    <div class="fg"><label class="f">달성 여부${sel(b+".status",["","달성","부분 달성","미달성"])}</label><label class="f">환류${sel(b+".fb",["","유지","개선"])}</label></div>
    <label class="f">${esc(y.cur)} 계획 (→ 계획서 총괄표)${ta(b+".next","",2)}</label><label class="f">${esc(y.next)} 계획${ta(b+".next2","",2)}</label>
    <div class="fg"><label class="f">전년 보고서 쪽${inp(b+".p1",{ph:"p.7"})}</label><label class="f">금년 보고서 쪽${inp(b+".p2",{ph:"p.10"})}</label><label class="f">계획서 쪽${inp(b+".p3",{ph:"p.00"})}</label></div>
    <div class="fg"><label class="f">신구대조 변경유형${sel(b+".chg",["유지","수정"])}</label><label class="f">변경 전 과제명${inp(b+".oldName")}</label></div>${t.chg==="수정"?`<label class="f">변경 사유 및 내용${inp(b+".chgNote")}</label>`:""}</div>`}).join("")||`<div class="panel small muted">지정된 과제가 없습니다.</div>`}</div></div>`}).join("")}</div>`; };
V.kpi=()=>{ const M=prof().modules.kpi; const av=dat().kpi.map(kpiAch).filter(isFinite);
  return head("보고서 · 계획서 · 개요표",M.label,`결과(outcome) 지표, 기준값이 있는 지표, 근거 있는 도전적 목표가 권장됩니다. 평균 달성도 <b class="num">${f1(av.length?av.reduce((a,b)=>a+b,0)/av.length:NaN)}%</b>`,`<button class="btn pri" data-act="rowAdd" data-arr="data.kpi" data-tpl='{"name":"새 지표","st":"신규","unit":"%","base":"","t1":"","t2":"","t3":"","act":"","formula":"","why":"","links":""}'>지표 추가</button>`)+
  `<div class="tw"><table class="t"><tr><th>#</th><th style="min-width:170px">지표명</th><th>구분</th><th>단위</th><th class="n">기준값</th><th class="n">1차 목표</th><th class="n">2차 목표</th><th class="n">3차 목표</th><th class="n">실적</th><th class="n">달성도</th><th>연계 과제</th><th></th></tr>${dat().kpi.map((k,i)=>{const a=kpiAch(k),b="data.kpi."+i;return `<tr><td>${i+1}</td><td class="in">${inp(b+".name",{aria:"지표명"})}</td><td class="in">${sel(b+".st",["기존","신규","수정"],"구분")}</td><td class="in" style="width:64px">${inp(b+".unit",{aria:"단위"})}</td>${["base","t1","t2","t3","act"].map(f=>`<td class="in" style="width:86px">${inp(b+"."+f,{num:1,aria:f})}</td>`).join("")}<td class="n num">${isFinite(a)?pill(a>=100?"ok":"warn",f1(a)+"%"):"-"}</td><td class="in" style="width:86px">${inp(b+".links",{aria:"연계 과제",ph:"6, 9"})}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="data.kpi" data-i="${i}">삭제</button></td></tr>`}).join("")}</table></div>
  <div class="grid2" style="margin-top:12px">${dat().kpi.map((k,i)=>`<div class="panel"><h3>${esc(k.name||"지표 "+(i+1))} 정의서</h3><label class="f">산출식${inp("data.kpi."+i+".formula")}</label><label class="f" style="margin-top:8px">설정 근거 · 세부지표${ta("data.kpi."+i+".why","",2)}</label></div>`).join("")}</div>`; };
V.finance=()=>{ const pr=prof(), D=dat(), y=pr.years; const b1=calcB1(), b2=calcB2(); const tp=n(D.meta.totalPrev);
  const rr=which=>pr.rules.map(r=>{const e=ruleEval(r,which);return e?`${pill("n",r.label)} ${pill(e.val<=e.lim?"ok":"bad",f1(e.val)+"% / "+e.lim+"%")}`:""}).join(" ");
  return head("보고서 요약·참고표 · 계획서 재정 투자계획",pr.modules.finance.label,"단위: 백만원. 프로필의 집행기준(비목 한도·이월·장비 승인)과 합계 일치 규칙을 자동으로 검증합니다.")+
  `<div class="stack"><div class="panel"><h3>${esc(y.prev)} 재정투자 현황 (예산·집행)</h3><div class="row" style="margin-bottom:8px">${rr("b1")}</div><div class="tw"><table class="t"><tr><th>비목</th><th class="n">예산(A)</th><th class="n">비중</th><th class="n">집행(B)</th><th class="n">집행률</th><th>집행 불가 항목</th></tr>${b1.rows.map(r=>`<tr><td>${esc(r.name)}</td><td class="in" style="width:110px">${inp(pth("data","b1",r.name,"bud"),{num:1,aria:"예산"})}</td><td class="n num">${f1(pct(r.bud,b1.tb))}%</td><td class="in" style="width:110px">${inp(pth("data","b1",r.name,"exe"),{num:1,aria:"집행"})}</td><td class="n num">${r.exeRaw===""?"-":f1(pct(r.exe,r.bud))+"%"}</td><td class="small muted">${esc((pr.forbid||{})[r.name]||"")}</td></tr>`).join("")}<tr class="sum"><td>합계</td><td class="n num">${won(b1.tb)}</td><td class="n num">100.0%</td><td class="n num">${won(b1.te)}</td><td class="n num">${f1(b1.rate)}%</td><td>${tp?pill(Math.abs(b1.tb-tp)<1?"ok":"bad",Math.abs(b1.tb-tp)<1?"최종 사업비와 일치":"최종 사업비 "+won(tp)+"과 차이"):pill("warn","기본정보에 전년도 사업비 입력")}</td></tr></table></div></div>
  ${pr.budgetAreas.length?`<div class="panel"><h3>영역별 예산</h3><div class="tw"><table class="t"><tr><th>영역</th>${pr.budgetYears.map(x=>`<th class="n">${esc(x)}</th>`).join("")}</tr>${pr.budgetAreas.map(k=>`<tr><td>${esc(k)}</td>${[0,1,2].map(j=>`<td class="in">${inp(pth("data","area3",k,j),{num:1,aria:k+j})}</td>`).join("")}</tr>`).join("")}<tr class="sum"><td>계</td>${[0,1,2].map(j=>`<td class="n num">${won(pr.budgetAreas.reduce((s,k)=>s+n((D.area3[k]||[])[j]),0))}</td>`).join("")}</tr></table></div></div>`:""}
  <div class="panel"><h3>${esc(y.cur)} 사업비 비목별 구성</h3><div class="row" style="margin-bottom:8px">${rr("b2")} <span class="small muted">기준: ${esc(y.cur)} 사업비 ${won(b2.base)}</span></div><div class="tw"><table class="t"><tr><th>비목명</th><th class="n">당해연도(A)</th><th class="n">이월금(B)</th><th class="n">합계</th><th class="n">총액 대비</th><th class="n">사업비 대비</th></tr>${b2.ent.map(e=>`<tr><td>${esc(e.k)}</td><td class="in" style="width:110px">${inp(pth("data","b2",e.k,0),{num:1,aria:e.k+" A"})}</td><td class="in" style="width:110px">${inp(pth("data","b2",e.k,1),{num:1,aria:e.k+" B"})}</td><td class="n num">${won(e.A+e.B)}</td><td class="n num">${f1(pct(e.A+e.B,b2.C))}%</td><td class="n num">${f1(pct(e.A+e.B,b2.base))}%</td></tr>`).join("")}<tr class="sum"><td>총계</td><td class="n num">${won(b2.A)}</td><td class="n num">${won(b2.B)}</td><td class="n num">${won(b2.C)}</td><td class="n num">100.0%</td><td></td></tr></table></div></div>
  ${pr.equipThreshold?`<div class="panel"><h3>장비·기자재 <span class="small muted">(${won(pr.equipThreshold)}백만원 이상 사전 승인)</span></h3><div class="tw"><table class="t"><tr><th>장비명</th><th>활용목적</th><th class="n">단가</th><th class="n">수량</th><th class="n">금액</th><th>승인</th><th></th></tr>${D.equip.map((e,i)=>`<tr><td class="in">${inp(`data.equip.${i}.name`,{aria:"장비명"})}</td><td class="in">${inp(`data.equip.${i}.purpose`,{aria:"목적"})}</td><td class="in" style="width:90px">${inp(`data.equip.${i}.unit`,{num:1,aria:"단가"})}</td><td class="in" style="width:70px">${inp(`data.equip.${i}.qty`,{num:1,aria:"수량"})}</td><td class="n num">${won(n(e.unit)*n(e.qty))}</td><td>${n(e.unit)>=pr.equipThreshold?pill("warn","승인 필요"):pill("n","-")}</td><td><button class="btn ghost sm" data-act="rowDel" data-arr="data.equip" data-i="${i}">삭제</button></td></tr>`).join("")}</table></div><button class="btn sm" style="margin-top:8px" data-act="rowAdd" data-arr="data.equip" data-tpl='{"name":"","purpose":"","unit":0,"qty":1}'>장비 추가</button></div>`:""}</div>`; };
V.bonus=()=>{ const m=prof().modules.bonus; const bo=calcBonus(); const B="data.bonus";
  return head("보고서 가산점 항목 · 증빙",m.label,esc(m.note||""))+`<div class="grid2"><div class="panel"><h3>입력 <span class="small muted">(명)</span></h3><div class="fg"><label class="f">산정 기준${sel(B+".scope",["입학정원","정원 내 모집인원"])}</label><label class="f">대상 연도${inp(B+".year")}</label><label class="f">전체 인원${inp(B+".total",{num:1})}</label>${(m.excl||[]).map((l,i)=>`<label class="f">${esc(l)}${inp(B+".ex."+i,{num:1})}</label>`).join("")}<label class="f">${esc(m.t1||"유형1")}${inp(B+".t1",{num:1})}</label><label class="f">${esc(m.t2||"유형2")}${inp(B+".t2",{num:1})}</label></div></div>
  <div class="panel"><h3>계산 결과</h3><div class="grid3"><div class="stat"><span class="small muted">모수</span><span class="v">${won(bo.mo)}</span></div><div class="stat"><span class="small muted">${esc(m.rowLabel)}</span><span class="v">${f1(bo.r1)}%</span></div><div class="stat"><span class="small muted">${esc(m.colLabel)}</span><span class="v">${f1(bo.sum)}%</span></div><div class="stat"><span class="small muted">예상 가점</span><span class="v" style="color:var(--accent)">${bo.pts==null?"-":bo.pts+"점"}</span></div></div>
  <div class="tw" style="margin-top:10px"><table class="t"><tr><th>${esc(m.rowLabel)} \\ ${esc(m.colLabel)}</th>${["",...m.colEdges].map((e,j,a)=>`<th class="n">${j===0?"0":a[j]}~${a[j+1]||""}</th>`).join("")}</tr>${m.table.map((r,i)=>`<tr><th>${i===0?"0":m.rowEdges[i-1]}~${m.rowEdges[i]||""}</th>${r.map((v,j)=>`<td class="n num" style="${i===bo.ri&&j===bo.ci&&bo.pts!=null?"background:var(--accent);color:var(--accent-ink);font-weight:700":""}">${v==null?"-":v}</td>`).join("")}</tr>`).join("")}</table></div></div></div>`; };
V.gov=()=>{ const M=prof().modules.gov; return head("보고서 성과관리 · 계획서 추진체계",M.label,`필수 구성: ${(M.required||[]).map(r=>esc(r.label)+"("+esc(r.match)+")").join(", ")||"없음"}. 운영 성과는 개최 횟수가 아닌 개선된 점 중심으로 적습니다.`,`<button class="btn pri" data-act="rowAdd" data-arr="data.gov" data-tpl='{"name":"새 위원회","func":"","members":"","y1":"","y2":"","out":""}'>조직 추가</button>`)+
  `<div class="grid2">${dat().gov.map((g,i)=>{const b="data.gov."+i;const req=(M.required||[]).filter(r=>new RegExp(r.match).test(g.name));return `<div class="taskcard"><div class="hd"><span class="no">${"①②③④⑤⑥⑦⑧⑨"[i]||i+1}</span><b>${esc(g.name)}</b><span style="flex:1"></span>${req.map(r=>pill(new RegExp(r.must).test(g.members||"")?"ok":"bad",r.label+(new RegExp(r.must).test(g.members||"")?" 포함":" 필수"))).join(" ")}<button class="btn ghost sm" data-act="rowDel" data-arr="data.gov" data-i="${i}">삭제</button></div><div class="fg"><label class="f">조직명${inp(b+".name")}</label><label class="f">주요기능${inp(b+".func")}</label></div><label class="f">구성${inp(b+".members")}</label><div class="fg"><label class="f">전년도 운영실적${inp(b+".y1")}</label><label class="f">금년도 운영계획${inp(b+".y2")}</label></div><label class="f">주요 성과(Outcome)${ta(b+".out","",2)}</label></div>`}).join("")}</div>`; };

/* ── 문서 작성 (프로필 목차) ── */
V.doc=(docId)=>{ const doc=docById(docId); if(!doc)return head("문서","문서를 찾을 수 없습니다",""); const secs=visibleSecs(doc).filter(s=>s.kind!=="head"); if(!secs.find(s=>s.id===curSec))curSec=(secs[0]||{}).id;
  const s=doc.sections.find(x=>x.id===curSec); const pr=prof(); if(!s)return head(doc.name,doc.name,"목차가 없습니다. 사업 구조 설정 → 문서·목차에서 항목을 추가하세요.");
  const b=pth("data","sec",doc.id,s.id); const area=pr.evalAreas.find(a=>a.id===s.evalArea); const to=[]; pr.docs.forEach(d=>d.sections.forEach(x=>{if(x.from.includes(doc.id+":"+s.id))to.push({d,x})}));
  let body="";
  if(s.kind==="text"){ const dr=draftFrom(s); body=draftBoxHTML(doc,s)+(dr?`<details><summary class="small">연결 원천 초안 보기</summary><div class="guide pre" style="white-space:pre-wrap;margin-top:6px">${esc(dr)}</div><button class="btn sm" style="margin-top:6px" data-act="copyDraft" data-doc="${esc(doc.id)}" data-sec="${esc(s.id)}">초안을 본문으로 복사</button></details>`:"")+`<label class="f">본문${dr?" (비워 두면 연결 원천 초안 사용)":""}${ta(b+".text","작성방법을 참고해 개조식으로 작성",12)}</label>`; }
  else if(s.kind==="pp"){ const ts=s.group?tasksBy(s.group):[]; body=draftBoxHTML(doc,s)+(s.group?`<div class="row">${ts.map(t=>`<span class="chip">${esc(t.name)} ${KEYMARK()}</span>`).join("")||pill("bad",pr.modules.tasks.label+" 미지정")}<button class="btn ghost sm" data-go="tasks">${esc(pr.modules.tasks.label)} 관리</button></div>`:"")+pr.ppFields.map(f=>f.short?`<label class="f">${esc(f.l)}${inp(b+"."+f.k)}</label>`:`<label class="f">${esc(f.l)}${ta(b+"."+f.k,"",5)}</label>`).join(""); }
  else if(s.kind==="derived"){ body=`<p class="small">연결된 보고서 항목의 계획과 ${esc(pr.modules.tasks.label)}에서 자동으로 만들어집니다.</p><div class="docwrap"><div class="doc" style="padding:24px">${derivedHTML(s)}</div></div>`; }
  else { const go={tasks:"tasks",kpi:"kpi",gov:"gov",budget:"finance",bonus:"bonus",summary:"home"}[s.src]; body=`<p class="small">이 항목은 공통 데이터에서 자동으로 만들어집니다. ${go?`<button class="btn sm" data-go="${go}">데이터 편집</button>`:""}</p><label class="f">표 앞에 넣을 서술(선택)${ta(b+".text","",3)}</label><div class="docwrap"><div class="doc" style="padding:24px">${autoHTML(s.src,doc)||'<p class="empty">[공통 데이터 종류가 지정되지 않았습니다]</p>'}</div></div>`; }
  return head(doc.name+(doc.due?" · "+doc.due:""),`${s.no} ${s.title}`,"")+
  `<div class="secnav">${secs.map(x=>{const st=secStatus(doc,x);return `<button class="btn sm ${x.id===curSec?"on":""}" data-sec="${esc(x.id)}" title="${esc(x.title)}"><span class="dot ${st}" style="display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px;vertical-align:middle"></span>${esc(x.no||x.title.slice(0,8))}</button>`}).join("")}</div>
  <div class="grid2" style="grid-template-columns:minmax(0,2fr) minmax(240px,1fr)"><div class="panel stack" style="gap:12px">${body}</div><div class="stack">
  ${s.guide.length?`<div class="guide"><b>【작성방법】</b><ol>${s.guide.map(g=>`<li>${esc(g)}</li>`).join("")}</ol></div>`:""}
  <div class="guide"><b>기본계획 평가요소</b><p style="margin:4px 0 0">${area?`${esc(area.name)} ${area.pts?`(${area.bonus?"+":""}${area.pts})`:""} — ${esc(area.desc)}`:"연결된 평가영역 없음"}</p>${area&&area.focus.length?`<ul style="margin:4px 0 0;padding-left:18px">${area.focus.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:""}</div>
  <div class="guide"><b>연결</b>${s.from.length?`<p style="margin:4px 0 0">원천: ${s.from.map(r=>{const x=secRef(r);return x?esc(x.doc.name+" "+x.sec.no+" "+x.sec.title):esc(r)}).join(" · ")}</p>`:""}${to.length?`<p style="margin:4px 0 0">다음으로: ${to.map(x=>esc(x.d.name+" "+x.x.no+" "+x.x.title)).join(" · ")}</p>`:""}${!s.from.length&&!to.length?'<p style="margin:4px 0 0">연결 없음</p>':""}</div></div></div>`; };

/* ── 문서 생성·내보내기 ── */
function diffHTML(){ return `<h2>핵심과제 신구대조표</h2><p>${esc(ORG())}</p><table><tr><th>구분</th><th>No</th><th>전년도 과제명</th><th>쪽</th><th>변경유형</th><th>변경 후 과제명</th><th>변경사유 및 내용</th><th>쪽</th></tr>${taskGroups().map(a=>{const ts=tasksBy(a.area);return ts.map((t,j)=>`<tr>${j===0?`<td rowspan="${ts.length}">${esc(a.sec)} ${esc(a.area)}</td>`:""}<td>${esc(t.no)}</td><td>${esc(t.oldName||t.name)}</td><td>${esc(t.p1)}</td><td>${esc(t.chg)}</td><td>${esc(t.name)}</td><td>${esc(t.chgNote||"해당사항 없음")}</td><td>${esc(t.p2)}</td></tr>`).join("")}).join("")}</table>`; }
V.out=()=>{ const pr=prof(); const tabs=pr.docs.map(d=>[d.id,d.name]).concat(pr.modules.tasks.on?[["__diff","신구대조표"]]:[]); if(!tabs.find(t=>t[0]===outTab))outTab=(tabs[0]||[""])[0];
  const html=outTab==="__diff"?diffHTML():docById(outTab)?docHTML(docById(outTab)):"<p>문서가 없습니다.</p>";
  return head("문서 생성","문서 미리보기 · 내보내기","서식 규격(본문 12pt, 줄간격 160%, 고딕)에 맞춘 미리보기입니다. ‘본문 복사’ 후 한글·워드 서식 파일에 붙여넣으면 표 구조가 유지됩니다. HTML로 저장한 파일은 한글과 워드에서 바로 열립니다. 붉은 칸은 아직 작성되지 않은 부분, 노란 칸은 플랫폼이 제시한 내용(안)입니다.",
  `<div class="row"><button class="btn pri" data-act="copyDoc">본문 복사</button><button class="btn" data-act="saveDoc">HTML 문서 저장</button><button class="btn" data-act="exportProject">사업 데이터 저장(JSON)</button></div>`)+batchBoxHTML()+
  `<div class="tabs">${tabs.map(([k,t])=>`<button class="tab ${outTab===k?"on":""}" data-otab="${esc(k)}">${esc(t)}</button>`).join("")}</div><div class="docwrap"><div class="doc" id="docOut">${html}</div></div>`; };

function render(keep){ const y=window.scrollY; renderTop(); renderNav(); let h;
  if(!P)h=V.welcome(); else if(cur==="newproj")h=V.newproj(false); else if(cur.startsWith("doc:"))h=V.doc(cur.split(":")[1]); else h=(V[cur]||V.home)();
  if(P&&P.demo)h=`<div class="demobar"><b>데모 모드</b><span>가상 데이터입니다. 입력·수정은 이 화면에서만 반영되고 저장되지 않습니다.</span><span style="flex:1"></span>${TOURI<0?'<button class="btn sm" data-act="tourResume">안내 다시 보기</button>':""}<button class="btn sm" data-act="exitDemo">데모 종료</button></div>`+h;
  $("#main").innerHTML=h; renderTour(); if(keep)window.scrollTo(0,y); else window.scrollTo(0,0);
  if(cur==="setup")getSample().then(s=>{const e=$("#sampleNote");if(e)e.textContent=s?"Claude 분석은 이 페이지를 보는 사람의 Claude 사용량을 씁니다. 처음 누를 때 허용을 묻습니다.":"이 보기에서는 Claude 분석을 쓸 수 없습니다(로컬 파일 등). 규칙 분석 후 직접 고쳐 주세요.";const b=$("#btnClaude");if(b&&!s)b.disabled=true;}); }
function renderTour(){ const el=$("#tour"); if(!P||!P.demo||TOURI<0||!TOUR[TOURI]){el.hidden=true;return;} const s=TOUR[TOURI]; el.hidden=false;
  el.innerHTML=`<div class="row" style="justify-content:space-between"><span class="tstep">데모 안내 ${TOURI+1} / ${TOUR.length}</span><button class="btn ghost sm" data-act="tourClose" aria-label="안내 닫기">닫기</button></div><h4>${esc(s.t)}</h4><p>${esc(s.b)}</p>${s.act?`<button class="btn pri sm" data-act="${esc(s.act)}" ${s.actData?Object.entries(s.actData).map(([k,x])=>`data-${k}="${esc(x)}"`).join(" "):""}>${esc(s.actLabel)}</button>`:""}<div class="row" style="justify-content:space-between"><div class="dots">${TOUR.map((x,i)=>`<i class="${i===TOURI?"on":""}"></i>`).join("")}</div><div class="row" style="gap:6px"><button class="btn sm" data-act="tourPrev" ${TOURI===0?"disabled":""}>이전</button><button class="btn sm pri" data-act="tourNext">${TOURI===TOUR.length-1?"마치기":"다음"}</button></div></div>`; }
function go(t){ if(t.startsWith("doc:")){const p=t.split(":");cur="doc:"+p[1];if(p[2])curSec=p[2];} else cur=t; try{history.replaceState(null,"","#"+cur.replace(/[^\w-]/g,"-"))}catch(e){} render(); }
